apiVersion: apps/v1
kind: Deployment
metadata:
  name:  htbp-service-sms
  namespace: default
  labels:
    app:  htbp-service-sms
spec:
  selector:
    matchLabels:
      app: htbp-service-sms
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  htbp-service-sms
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  service-sms
        image: htbp-registry:5000/service-sms
        # imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 8204
      imagePullSecrets:
      - name: regcred

#kubectl create secret docker-registry regcred --docker-server=htbp-registry --docker-username=htbp --docker-password=pw_htbp --docker-email=admin@admin.com

