apiVersion: v1
kind: Service
metadata:
  name: htbp-redis
spec:
  ports:
  - port: 6379
  selector:
    app: htbp-redis
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htbp-redis
spec:
  selector:
    matchLabels:
      app: htbp-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: htbp-redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        
            