apiVersion: v1
kind: Service
metadata:
  name: yygh-rebbitmq
spec:
  ports:
  - port: 5672
    name: rebbitmq1
  - port: 15672
    name: rebbitmq2
  selector:
    app: yygh-rebbitmq
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yygh-rebbitmq
spec:
  selector:
    matchLabels:
      app: yygh-rebbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yygh-rebbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rebbitmq
        ports:
        - containerPort: 5672
          name: rebbitmq1
        - containerPort: 15672
          name: rebbitmq2
            