apiVersion: v1
kind: Service
metadata:
  name: yygh-mongo
spec:
  ports:
  - port: 27017
  selector:
    app: yygh-mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yygh-mongo
spec:
  selector:
    matchLabels:
      app: yygh-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yygh-mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc


#kubectl run -it --rm --image=mysql --restart=Never mysql-client -- mysql -h yygh-mysql -ppw_yygh
