apiVersion: v1
kind: Service
metadata:
  name: yygh-nacos
spec:
  ports:
  - port: 8848
  selector:
    app: yygh-nacos
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yygh-nacos
spec:
  selector:
    matchLabels:
      app: yygh-nacos
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: yygh-nacos
    spec:
      containers:
      - image: nacos/nacos-server:2.0.2
        name: nacos
        env:
          # Use secret in real usage
        - name: MODE
          value: standalone
        ports:
        - containerPort: 8848
          name: nacos
        
            