apiVersion: v1
kind: Service
metadata:
  name: htbp-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: htbp-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: htbp-mysql
spec:
  selector:
    matchLabels:
      app: htbp-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: htbp-mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: pw_htbp
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc


#kubectl run -it --rm --image=mysql --restart=Never mysql-client -- mysql -h htbp-mysql -ppw_htbp
