apiVersion: v1
kind: PersistentVolume
metadata:
  name: htbp-kaniko-pv
  namespace: default
  labels:
    app: htbp-kaniko-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/k8s/kaniko"
    server: 192.168.1.20
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-pvc
  namespace: default
  labels:
    app: kaniko-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi