apiVersion: v1
kind: PersistentVolume
metadata:
  name: htbp-mongo-pv
  namespace: default
  labels:
    app: htbp-mongo-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/k8s/mongo"
    server: 192.168.1.20
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: default
  labels:
    app: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi