apiVersion: v1
kind: PersistentVolume
metadata:
  name: htbp-registry-pv
  namespace: default
  labels:
    app: htbp-registry-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: "/data/k8s/registry"
    server: 192.168.1.20
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: default
  labels:
    app: registry-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi